name: Build

on:
  pull_request:
  push:
    branches: [ 'main', 'develop' ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  CMake:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          TARGET_PATH=${{ runner.workspace }}/neuron/target/release
          echo "TARGET_PATH=$TARGET_PATH" >> $GITHUB_ENV

      - name: Prepare
        run: |
          mkdir -p "${{ env.TARGET_PATH }}"

      - name: Configure
        run: |
          cd "${{ env.TARGET_PATH }}"
          cmake ../../

      - name: Build
        run: |
          cd "${{ env.TARGET_PATH }}"
          cmake --build . --parallel 4

  Make:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install ARM Toolchain"
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10-2020-q4'

      - name: Build
        run: make
