name: test

on:
    pull_request:
    push:
        branches: ['main', 'develop']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Test"